version: '3'

services:
  web:
    build: ./web/.
    ports:
      - "8080:80" # Page web
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - db
    environment:
      - PORT=8082
      - DB_HOST=concerino-postgres
      - DB_CONNECTION=pgsql
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - DB_NAME=concerino
  db:
    image: postgres:14.0
    container_name: concerino-postgres
    ports:
      - "5432:5432" # DB
    volumes:
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=concerino
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      #- POSTGRES_INITDB_ARGS='--encoding=UTF-8'