version: '3'

services:
  web:
    build: ./web/.
    ports:
      - "9090:80" # Page web
    volumes:
      - ./web/src:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=concerino-postgres
      - DB_CONNECTION=pgsql
      - DB_NAME=concerino
      - DB_USER=postgres
      - DB_PASSWORD=admin
  db:
    image: postgres:14.0
    container_name: concerino-postgres
    ports:
      - "6666:5432" # DB
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=concerino
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
volumes:
  pgdata:
